SilverScreener/Models/Theater.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SilverScreener.Models
{
    public class Theater
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TheaterId { get; set; }

        [Required]
        [Display(Name = "Theater Name")]
        public string TheaterName { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }
    }
}

SilverScreener/ViewModels/TheaterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SilverScreener.ViewModels
{
    public class TheaterViewModel
    {
        public TheaterViewModel()
        {
            this.Movies = new List<MovieViewModel>();
        }

        public int TheaterId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }

        public List<MovieViewModel> Movies { get; set; }
    }
}

SilverScreener/Controllers/TheaterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SilverScreener.Dto;
using SilverScreener.Models;
using SilverScreener.ViewModels;

namespace SilverScreener.Controllers
{
    public class TheaterController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Movies
        [HttpGet]
        public ActionResult Index()
        {
            var model = TheaterManager.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Details(int? theaterId)
        {
            if (!theaterId.HasValue)
            {
                return HttpNotFound();
            }
            
            var model = TheaterManager.GetByTheaterId(theaterId.Value);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TheaterViewModel model)
        {
            TheaterManager.Add(model);

            return RedirectToAction("Index");
        }
        //[HttpPost]
        //public ActionResult Search(string theaterSearch)
        //{
        //    var results = TheaterManager.Get(theaterSearch);

        //     return PartialView("Partials/_SearchResults", results);
        // }
    }
}

SilverScreener/Views/Theater/Create.cshtml
@model SilverScreener.ViewModels.TheaterViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Theater</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <input type="submit" value="Add Theater" class="btn btn-default" />
        </div>
    </div>
}

SilverScreener/Views/Theater/Details.cshtml
@model TheaterViewModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="row">
    <div class="col-md-12">
        <h2>@Model.Name</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p>Location: <strong>@Model.Location</strong></p>
    </div>
</div>

<div id="movies">
    @if (!Model.Movies.Any())
    {
        <p> Now Movies Available. Add some here</p>
    }
</div>

SilverScreener/Views/Theater/Index.cshtml
@model IEnumerable<SilverScreener.ViewModels.TheaterViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Theaters</h2>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Search", "Theater", FormMethod.Post, new { @class = "search-form" }))
        {
            <div class="col-md-12">
                <label for="theaterSearch" class="sr-only">Search</label>
                <input type="text" id="theaterSearch" name="theaterSearch" placeholder="Search for your Movie Theater" class="form-control search-box" style="float: left; margin-right: 5px;"> <input type="submit" id="btnSearch" class="btn btn-primary" value="Search">
                
            </div>
        }
    </div>
    <div id="theater-list">
        @foreach (var item in Model)
        {
            @Html.Partial("../Partials/_TheaterDetails", item)
        }
    </div>
</div>

<div class="row">
    @Html.ActionLink("+ Add Movie Theater", "Create", "Theater")
</div>






<script>
    $(document).ready(function() {
        $("#btnSearch").click(function(e) {
            e.preventDefault();

            $.ajax({
                url: $("form.search-form").attr("action"),
                data: {
                    theaterSearch: $("#theaterSearch").val()
                },
                type: "POST",
                dataType: "html"
            }).done(function(response) {
                $("#theater-list").html(response);
            });
        });
    });
</script>